In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/jigsaw-toxic-comment-classification-challenge/train.csv')

In [3]:
df

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [5]:
test_df = pd.read_csv('../data/jigsaw-toxic-comment-classification-challenge/test.csv')

In [6]:
test_df

                      id                                       comment_text
0       00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1       0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2       00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3       00017563c3f7919a  :If you have a look back at the source, the in...
4       00017695ad8997eb          I don't anonymously edit articles at all.
...                  ...                                                ...
153159  fffcd0960ee309b5  . \n i totally agree, this stuff is nothing bu...
153160  fffd7a9a6eb32c16  == Throw from out field to home plate. == \n\n...
153161  fffda9e8d6fafa9e  " \n\n == Okinotorishima categories == \n\n I ...
153162  fffe8f1340a79fc2  " \n\n == ""One of the founding nations of the...
153163  ffffce3fb183ee80  " \n :::Stop already. Your bullshit is not wel...

[153164 rows x 2 columns]

In [7]:
test_df_labels = pd.read_csv('../data/jigsaw-toxic-comment-classification-challenge/test_labels.csv')

In [8]:
test_df_labels

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1
1,0000247867823ef7,-1,-1,-1,-1,-1,-1
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,-1,-1,-1,-1,-1,-1
153160,fffd7a9a6eb32c16,-1,-1,-1,-1,-1,-1
153161,fffda9e8d6fafa9e,-1,-1,-1,-1,-1,-1
153162,fffe8f1340a79fc2,-1,-1,-1,-1,-1,-1
153163,ffffce3fb183ee80,-1,-1,-1,-1,-1,-1

In [9]:
is_scored =  test_df_labels['toxic']!=-1

In [10]:
test_data = test_df[is_scored]
test_data_labels = test_df_labels[is_scored]

In [11]:
test_data_labels

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
5,0001ea8717f6de06,0,0,0,0,0,0
7,000247e83dcc1211,0,0,0,0,0,0
11,0002f87b16116a7f,0,0,0,0,0,0
13,0003e1cccfd5a40a,0,0,0,0,0,0
14,00059ace3e3e9a53,0,0,0,0,0,0
...,...,...,...,...,...,...,...
153150,fff8f64043129fa2,0,0,0,0,0,0
153151,fff9d70fe0722906,0,0,0,0,0,0
153154,fffa8a11c4378854,0,0,0,0,0,0
153155,fffac2a094c8e0e2,1,0,1,0,1,0
153156,fffb5451268fb5ba,0,0,0,0,0,0

In [12]:
test_data

                      id                                       comment_text
5       0001ea8717f6de06  Thank you for understanding. I think very high...
7       000247e83dcc1211                   :Dear god this site is horrible.
11      0002f87b16116a7f  "::: Somebody will invariably try to add Relig...
13      0003e1cccfd5a40a  " \n\n It says it right there that it IS a typ...
14      00059ace3e3e9a53  " \n\n == Before adding a new product to the l...
...                  ...                                                ...
153150  fff8f64043129fa2  :Jerome, I see you never got around to thisâ€¦! ...
153151  fff9d70fe0722906  ==Lucky bastard== \n http://wikimediafoundatio...
153154  fffa8a11c4378854  ==shame on you all!!!== \n\n You want to speak...
153155  fffac2a094c8e0e2  MEL GIBSON IS A NAZI BITCH WHO MAKES SHITTY MO...
153156  fffb5451268fb5ba  " \n\n == Unicorn lair discovery == \n\n Suppo...

[63978 rows x 2 columns]

In [13]:
X_train = df['comment_text']
Y_toxic_train = df['toxic']
Y_severe_toxic_train = df['severe_toxic']
Y_obscene_train = df['obscene']
Y_threat_train = df['threat']
Y_insult_train = df['insult']
Y_identity_hate_train = df['identity_hate']
X_test = test_data['comment_text']
Y_toxic_test = test_data_labels['toxic']
Y_severe_toxic_test = test_data_labels['severe_toxic']
Y_obscene_test = test_data_labels['obscene']
Y_threat_test = test_data_labels['threat']
Y_insult_test = test_data_labels['insult']
Y_identity_hate_test = test_data_labels['identity_hate']

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
# create a count vectorizer object 
count_vect = CountVectorizer()
count_vect.fit(X_train)

print(count_vect.vocabulary_)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [17]:
print(count_vect.vocabulary_)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
# transform the training and validation data using count vectorizer object
xtrain_count =  count_vect.transform(X_train)
xtest_count =  count_vect.transform(X_test)

In [19]:
print(xtrain_count.toarray().shape)

(159571, 190339)